Made scan-config command

diff --git a/src/timetraveler b/src/timetraveler
--- a/src/timetraveler
+++ b/src/timetraveler
@@ -2,17 +2,23 @@
 
 set -e
 D="$(dirname "$(readlink -f "$0")")"
-if [ ! -e "$D/timetraveler.lib.sh" ]; then
+for libdir in "$TT_LIBDIR" /usr/share/timetraveler "$D"; do
+    if [ -e "$libdir/timetraveler.lib.sh" ]; then
+        . "$libdir/timetraveler.lib.sh"
+        lib_loaded=true
+        break
+    fi
+done
+if [ "$lib_loaded" != "true" ]; then
     >&2 echo
-    >&2 echo "E: Expected to find timetraveler.lib.sh in $D, but didn't"
+    >&2 echo "E: Couldn't find timetraveler libraries! Are you sure you've installed"
+    >&2 echo "   timetraveler correctly?"
     >&2 echo
     exit 1
-else
-    . "$D/timetraveler.lib.sh"
 fi
 
 
-VERSION=0.1.0
+export TT_VERSION=0.1.1
 
 # Initial loop to gather global options and main command
 while test $# -gt 0; do
@@ -31,7 +37,7 @@ while test $# -gt 0; do
 
         --version)
             echo
-            echo "$(basename "$0") version $VERSION"
+            echo "$(basename "$0") version $TT_VERSION"
             echo
             echo "See readme and license information, file bug reports, and view source code at"
             echo "https://github.com/kael-shipman/timetraveler"
@@ -65,13 +71,18 @@ fi
 
 # Run subcommand
 
-if [ -e "$D/timetraveler-$COMMAND" ]; then
-    "$D/timetraveler-$COMMAND" $@
-else
-    >&2 echo
-    >&2 echo "E: Couldn't find subcommand timetraveler-$COMMAND in $D!"
-    >&2 echo
-    >&2 echo "This is an error that the maintainer should fix...."
-    >&2 echo
+# See if it's on the path
+if ! CMD="$(command -v "timetraveler-$COMMAND")"; then
+    # Otherwise, see if it's in the same directory as the current file
+    CMD="$D/timetraveler-$COMMAND"
+    if [ ! -e "$CMD" ]; then
+        >&2 echo
+        >&2 echo "E: Couldn't find subcommand timetraveler-$COMMAND! Are you sure timetraveler"
+        >&2 echo "   is properly installed?"
+        >&2 echo
+        exit 3
+    fi
 fi
+
+"$CMD" $@
 
diff --git a/src/timetraveler-backup b/src/timetraveler-backup
--- a/src/timetraveler-backup
+++ b/src/timetraveler-backup
@@ -2,28 +2,31 @@
 
 set -e
 D="$(dirname "$(readlink -f "$0")")"
-if [ ! -e "$D/timetraveler.lib.sh" ]; then
+for libdir in "$TT_LIBDIR" /usr/share/timetraveler "$D"; do
+    if [ -e "$libdir/timetraveler.lib.sh" ]; then
+        . "$libdir/timetraveler.lib.sh"
+        lib_loaded=true
+        break
+    fi
+done
+if [ "$lib_loaded" != "true" ]; then
     >&2 echo
-    >&2 echo "E: Expected to find timetraveler.lib.sh in $D, but didn't"
+    >&2 echo "E: Couldn't find timetraveler libraries! Are you sure you've installed"
+    >&2 echo "   timetraveler correctly?"
     >&2 echo
     exit 1
-else
-    . "$D/timetraveler.lib.sh"
 fi
 
 
 function show_backup_help() {
     {
         echo
-        echo "USAGE"
-        echo 
-        echo "timetraveler backup (-h|--help) [profile]|all"
+        echo "SYNOPSIS"
+        echo "      timetraveler backup (-h|--help) [profile]|all"
         echo
-        echo
-        echo " OPTIONS"
-        echo
-        echo "    -r|--rsync-command                             The rsync command to use, if not on standard path"
-        echo "    -o|--rsync-options                             Extra options to append to the rsync command"
+        echo "OPTIONS"
+        echo "      -r|--rsync-command                             The rsync command to use, if not on standard path"
+        echo "      -o|--rsync-options                             Extra options to append to the rsync command"
         echo
     }
 }
@@ -35,7 +38,7 @@ fi
 RSYNC_OPTIONS=
 
 
-# Initial loop to gather global options and main command
+# Loop to gather options
 while test $# -gt 0; do
     case "$1" in
         -r|--rsync-command)
@@ -84,37 +87,11 @@ if [ -z ${PROFILE+x} ]; then
 fi
 
 
-# Verify config file exists and we have necessary dependencies to proceed
 
-CONF_DIR="$HOME/.config/timetraveler"
-CONF_FILE="$CONF_DIR/config"
-if [ ! -d "$CONF_DIR" ]; then
-    mkdir -p "$CONF_DIR"
-fi
+# Parse config file and check dependencies
 
-if [ ! -e "$CONF_FILE" ]; then
-    >&2 echo
-    >&2 echo "E: You haven't created a config file yet!"
-    >&2 echo
-    >&2 echo "   Please create the file ~/.config/timetraveler/config and put your timetraveler"
-    >&2 echo "   config, including backup profiles, in it. (See https://github.com/kael-shipman/timetraveler"
-    >&2 echo "   for more information about config.)"
-    >&2 echo
-    exit 3
-else
-    if ! jq="$(command -v jq)"; then
-        >&2 echo
-        >&2 echo "E: You must have \`jq\` installed on your machine to use timetraveler."
-        >&2 echo
-        exit 4
-    fi
-fi
-
-
-
-# Parse config file
-
-parse_config "$CONF_FILE"
+verify_config # Sets TT_CONF_FILE
+parse_config "$TT_CONF_FILE" # Sets CNF_PRFS* variables
 
 
 
